-- FIXME: Correlacionar Avies com Provisões
-- Lista de artigos Firmes não rececionados
-- AJBZST > FERM OR PROV
-- AJE4ST > RECEIVED OUI OR NO
-- HPO - TODOS OS PEDIDOS FIRMES QUE NÃO FORAM ENTREGUES
-- SUP - TODOS OS ASNs ENVIADOS PELOS FORNECEDORES
-- THKSPERNS

SELECT HPO.CODE, HPO.COMPONENT, HPO.PROVDATE, HPO.PROVQTF, HPO.FORNSACHA, HPO.FORNECEDOR, SUP.DN, SUP.SENDDATE, SUP.PLACE, SUP.STATUS, SUP.SENDQTF

FROM (SELECT DISTINCT PROV.AJARCD AS CODE, PROV.AJD5CD AS COMPONENT, 
	DATE(CONCAT('20', substr(PROV.AJAFDT, 2,2))||'-'||substr(PROV.AJAFDT, 4,2)||'-'||substr(PROV.AJAFDT, 6,2)) AS PROVDATE,
	PROV.AJAIQT AS PROVQTF, APRO.AEGGCD AS APROCODE, FORN.ASAUCD AS FORNSACHA, FORN.ASAHTX AS FORNECEDOR
	
FROM AUTO.YSACHAHPO.YDAJREP PROV

LEFT JOIN  AUTO.YSACHAHPO.YDAEREP APRO
ON APRO.AEARCD = PROV.AJARCD

LEFT JOIN AUTO.YSACHAHPO.YDASREP FORN
ON APRO.AEARCD = FORN.ASARCD

WHERE PROV.AJBZST = 'F' AND PROV.AJE4ST = 'N') AS HPO

FULL JOIN (SELECT ASN.HIARCD AS CODE, ASN.HIUNCD AS DN, ART.HJD5CD AS COMPONENT, ART.HJHONB AS SENDQTF, 
	DATE(CONCAT('20', substr(ASN.HIC5DT, 2,2))||'-'||substr(ASN.HIC5DT, 4,2)||'-'||substr(ASN.HIC5DT, 6,2)) AS SENDDATE, 
	ASN.HIUPCD AS PLACE, ASN.HITEST AS STATUS
	
FROM AUTO.YSACHAHPO.YDHIREP ASN

RIGHT JOIN AUTO.YSACHAHPO.YDHJREP ART
ON ART.HJUNCD = ASN.HIUNCD

WHERE ASN.HITEST < 4) AS SUP
ON SUP.COMPONENT = HPO.COMPONENT

ORDER BY HPO.PROVDATE
