-- FIXME: Correlacionar Avies com Provisões
-- Lista de artigos Firmes não rececionados

SELECT DISTINCT PROV.AJARCD AS CODE, PROV.AJD5CD AS COMPONENT, PROV.AJAFDT AS PROVDATE, PROV.AJAIQT AS PROVQTF, APRO.AEGGCD AS APROCODE, FORN.ASAUCD AS FORNSACHA, FORN.ASAHTX AS FORNECEDOR
FROM AUTO.YSACHAHPO.YDAJREP PROV

LEFT JOIN  AUTO.YSACHAHPO.YDAEREP APRO
ON APRO.AEARCD = PROV.AJARCD

LEFT JOIN AUTO.YSACHAHPO.YDASREP FORN
ON APRO.AEARCD = FORN.ASARCD

WHERE PROV.AJBZST = 'F' AND PROV.AJE4ST = 'N'


-- AJBZST > FERM OR PROV
-- AJE4ST > RECEIVED OUI OR NO
