-- Listagem PICK

SELECT DISTINCT T1.LLPPN AS ARTIGO
FROM AUTO.D805DATHPO.IC130M AS T1 
INNER JOIN (SELECT DISTINCT LLPPN AS ARTIGO2 FROM AUTO.D805DATHPO.IC130M  WHERE LLSTLC = 'PICK') T2
ON T2.ARTIGO2 = T1.LLPPN
WHERE T1.LLSTLC = 'MP-KANB'


-- Mais Condições

SELECT DISTINCT T1.LLPPN AS ARTIGO
FROM AUTO.D805DATHPO.IC130M AS T1 
INNER JOIN (SELECT DISTINCT LLPPN AS ARTIGO2 FROM AUTO.D805DATHPO.IC130M  WHERE LLSTLC = 'PICK') T2
ON T2.ARTIGO2 = T1.LLPPN
WHERE T1.LLSTLC = 'MP-KANB'
  AND (T1.LLBLT1 + T1.LLBLT2 + T1.LLBLT3 + LLBLT4 <> 0)
