-- Transferências mal feitas
-- Deveria ser transferido para PICK e foram transferidas para as linhas e/ou UAPs

SELECT DISTINCT TPO001.PO0101 AS ARTIGO, STOCK.LLSTLC AS PLACE, STOCK.QTD
FROM AUTO.D805DATHPO.TPO001 TPO001

INNER JOIN (
  SELECT DISTINCT LLPPN AS ARTIGOSTK, LLSTLC, (LLBLT1 + LLBLT2 + LLBLT3 + LLBLT4) AS QTD 
  FROM AUTO.D805DATHPO.IC130M  
  WHERE LLSTLC LIKE '%UAP%'
  ) STOCK
ON STOCK.ARTIGOSTK = TPO001.PO0101 

LEFT JOIN 
  
WHERE TPO001.PO0107 = '03'
  AND TPO001.PO0117 = 'PICK'
  AND (STOCK.QTD <> 0)
  
ORDER BY PLACE
